import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import { Printer } from "lucide-react";
import { Inspections } from "../api/client";
import StatusBadge from "../components/StatusBadge";

export default function Report() {
  const { id } = useParams();
  const [inspection, setInspection] = useState(null);

  useEffect(() => {
    Inspections.get(id).then(setInspection);
  }, [id]);

  if (!inspection) return <p className="text-sm text-ink/50 p-8">Loading…</p>;

  return (
    <div className="min-h-screen bg-[#EDEBE4] py-10 px-4">
      <div className="max-w-3xl mx-auto">
        <div className="no-print flex justify-end mb-4">
          <button
            onClick={() => window.print()}
            className="flex items-center gap-2 bg-[#152238] text-white px-4 py-2 text-sm rounded-lg hover:bg-[#1F3452]"
          >
            <Printer size={16} /> Print / Save as PDF
          </button>
        </div>

        <div className="bg-white border border-[#152238]/10 p-10 text-[#1C1C1C]">
          <div className="text-center border-b-2 border-[#152238] pb-4 mb-6">
            <p className="text-xs tracking-wide text-[#6B6B6B]">GOVERNMENT OF INDIA — LEGAL METROLOGY DIVISION</p>
            <h1 className="text-xl font-display font-semibold text-[#152238] mt-1">
              Statutory Compliance Assessment Report
            </h1>
            <p className="text-xs text-[#8A8A8A] mt-1">
              Issued under the Legal Metrology (Packaged Commodities) Rules, 2011
            </p>
          </div>

          <div className="grid grid-cols-2 gap-4 text-sm mb-6">
            <div>
              <p className="text-[#8A8A8A] text-xs">Product</p>
              <p className="font-medium">{inspection.productName}</p>
            </div>
            <div>
              <p className="text-[#8A8A8A] text-xs">Category</p>
              <p className="font-medium">{inspection.category.replace("_", " ")}</p>
            </div>
            <div>
              <p className="text-[#8A8A8A] text-xs">Inspecting Officer</p>
              <p className="font-medium">{inspection.officerName}</p>
            </div>
            <div>
              <p className="text-[#8A8A8A] text-xs">Date of Inspection</p>
              <p className="font-medium">{new Date(inspection.createdAt).toLocaleString()}</p>
            </div>
            <div>
              <p className="text-[#8A8A8A] text-xs">Report ID</p>
              <p className="font-medium">{inspection.id}</p>
            </div>
            <div>
              <p className="text-[#8A8A8A] text-xs">Overall Determination</p>
              <StatusBadge status={inspection.verdict} />
            </div>
          </div>

          {inspection.manualReview?.suggested && (
            <div className="border border-review/40 bg-review/10 text-[#7A5A00] text-xs px-4 py-3 mb-6 rounded">
              <strong>Manual verification recommended:</strong> {inspection.manualReview.reason}
            </div>
          )}

          <table className="w-full text-sm border-collapse mb-6">
            <thead>
              <tr className="border-b-2 border-[#152238] text-left">
                <th className="py-2 pr-2">Rule</th>
                <th className="py-2 pr-2">Requirement</th>
                <th className="py-2 pr-2">Evidence</th>
                <th className="py-2">Status</th>
              </tr>
            </thead>
            <tbody>
              {inspection.checks.map((c) => (
                <tr key={c.id} className="border-b border-[#152238]/10 align-top">
                  <td className="py-2 pr-2 font-medium">{c.id}</td>
                  <td className="py-2 pr-2 text-[#4A4A4A]">{c.requirement}</td>
                  <td className="py-2 pr-2 text-[#4A4A4A]">
                    {c.evidence || "—"}
                    {c.manualCheckSuggested && (
                      <span className="block text-[10px] text-[#7A5A00] mt-0.5">
                        ⚠ Low image confidence — verify manually
                      </span>
                    )}
                  </td>
                  <td className="py-2">
                    <StatusBadge status={c.status} />
                  </td>
                </tr>
              ))}
            </tbody>
          </table>

          <p className="text-xs text-[#8A8A8A] border-t border-[#152238]/10 pt-4">
            This is a prototype screening result generated by an automated assistance system. It does not
            constitute a final legal determination. Any enforcement action must be verified and authorized by a
            designated Legal Metrology Officer in accordance with the Legal Metrology Act, 2009 and the Legal
            Metrology (Packaged Commodities) Rules, 2011.
          </p>
        </div>
      </div>
    </div>
  );
}
